### PR TITLE
Added support for hsp4 kernels with kslide caching

### PR DESCRIPTION
**Pull request by userlandkernel**

### CODE REVIEW

**Comment by haiyuidesu** [comment]
how would you like to get kloader working if `tfp0` isn't declared (l.`213`)?

**Comment by userlandkernel** [comment]
Oopsy. Sorry, I uploaded the old code.
Let me fix it with care this time.

**Comment by haiyuidesu** [comment]
btw, if you really have nothing todo, you should replace and implement some things, as:
-> for `#define MACHO_HEADER_MAGIC`, set `0xfeedface`, `arm64` is `0xfeedfacf` (the result is the same, but you see the value..)
-> for `#define KERNEL_SEARCH_ADDRESS_IOS`, you wrote for the `STATIC` thing, iOS 10 address, why not also implementing iOS 9?: `0xfffffff007004000`
-> Implement kaslr slide: `#define KASLR_SLIDE 0x21000000`
for an exemple, see JSeals `kernelversionhack`.

**Comment by userlandkernel** [comment]
I don't get why you would take a static KASLR_SLIDE, but I'll have a look. I'll push some changes next week.
I know there are many improvements to be done in here.
Will work on that later ;)

**Comment by haiyuidesu** [comment]
you can close this PR, i did it on my free time, so I'll open one.

**Comment by userlandkernel** [comment]
Thanks @yumiistar am too busy to patch it so really appreciate your work!

**Comment by haiyuidesu** [comment]
here you go (I did a fork finally) https://github.com/yumiistar/ios-kexec-utils

**Pull request closed without merging**
